### ISSUE TITLE
Short recorded audio

### ISSUE THREAD

**Issue by mfaguilar** [axew3/phpBB-audio-video-to-post#2]
In my tests (desktop and mobile), it only allows 16 seconds of recorded audio. I don't know if there is some browser limitation, but I think it should allow at least 5 minutes.
Thanks for the work!

**Comment by axew3** [comment]
Hello! In this working example the length of the audio and so the resulting possible dimension of the file, **depend by the dimension of attachments you allow, into ACP**
Just increase the allowed dimension for attachments
